[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "apt-get update && apt-get install -y python3-pip chromium chromium-driver",
  "python3 -m pip install --upgrade pip",
  "python3 -m pip install -r requirements.txt"
]

[start]
cmd = "python3 forsalebyowner_selenium_scraper.py"

